"""Initial migration

Revision ID: 2111bf24f6b2
Revises: 
Create Date: 2024-04-23 00:41:14.005050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2111bf24f6b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('comment',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('toxic', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('severe_toxic', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('obscene', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('threat', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('insult', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('identity_hate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_censored', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('user')
    # ### end Alembic commands ###
